### ISSUE TITLE
Wrong default bucket name

### ISSUE THREAD

**Issue by jlarkin-noblis** [usdot-its-jpo-data-portal/cv_pilot_ingest#9]
In sandbox_to_csv.py, the default bucket name is set to 'test-usdot-its-cvpilot-public-data' vs 'usdot-its-cvpilot-public-data' so if you run it with out a bucket name it will not find data.  Also the 'threads' variable on line 194 is never used.

**Comment by chuehlien** [comment]
Thanks @jlarkin-noblis for the feedback. Closing this ticket since `sandbox_to_csv.py` is no longer in this repository, but we'll make sure to double check for unused variables.
